site_name: Helm Docs Test
site_url: https://helm-docs-test.com
theme:
  name: material
  logo: static/images/helm.svg
  favicon: static/images/helm-logo.svg
  language: en
  # font:
  #   text: Space Mono
plugins:
  - search
  # mkdocs-i18n plugin config:
  #
  # - i18n:
  #     default_language: 'en'
  #     languages:
  #       es: "Español"
  #       en: "English"
  #     translate_nav:
  #       es:
  #         English Section Label: "Spanish Section Label"

  #mkdocs-static-i18n plugin config:
  - i18n:
      docs_structure: suffix
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: es
          name: Español
          build: true
          # you have to recreate the nav for each locale
          # could lead to very long file
          nav:
            - index.es.md
            - Spanish Section Label:
              - lorem-ipsum.es.md
        - locale: pt
          name: Português
          build: true
          nav:
            - index.pt.md
            - Portuguese Section Label:
              - lorem-ipsum.pt.md
extra_css:
  - stylesheets/extra.css
nav:
  - index.md
  - English Section Label:
    - lorem-ipsum.md  
extra:
  extra:
    version:
      provider: mike
  alternate:
    - name: English
      link: /
      lang: en
    - name: Español
      link: /es/
      lang: es
    - name: Português
      link: /pt/
      lang: pt