site_name: Helm Docs Test
site_url: https://helm-docs-test.com
theme:
  name: material
  logo: static/images/helm.svg
  favicon: static/images/helm-logo.svg
  # font:
  #   text: Space Mono
extra_css:
  - stylesheets/extra.css